import React, { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import usePagination from '../../hooks/usePagination';

const CATEGORIES = ['Projects', 'Products', 'FAQ', 'Testimonials', 'Blogs', 'Messages', 'Company Settings'];

const DEFAULT_COMPANY_SETTINGS = {
  aboutUs: 'Nova Solar Solutions is dedicated to bringing sustainable, high-efficiency solar energy to homes and businesses globally.',
  address: '123 Solar Wave Avenue, Tech District, 45000',
  email: 'contact@novasolar.com',
  phone: '+1 (800) 555-0199',
  facebook: '',
  instagram: ''
};

const DUMMY_DATA_MAP = {
  Projects: [
    { id: 1, title: 'Modern Villa Installation', client: 'Residential (10 kW System)', description: 'Complete offset of electricity usage for a luxury property. Beautifully integrated flat-roof panels.', image: '/images/residential.png', status: 'Published', date: new Date().toISOString().split('T')[0] },
    { id: 2, title: 'Tech Park Mega-Install', client: 'Commercial (500 kW System)', description: 'Significant carbon reduction and massive cost savings for a modern commercial tech warehouse.', image: '/images/commercial.png', status: 'Published', date: new Date().toISOString().split('T')[0] }
  ],
  Products: [
    { id: 1, name: 'NovaPanel Pro Max', category: 'Solar Panel', price: '550W | 22.8% Efficiency', image: '/images/solar_panel.png', description: 'Our flagship monocrystalline solar panel designed for maximum residential output.', status: 'Published', date: new Date().toISOString().split('T')[0] },
    { id: 2, name: 'Smart Inverter V2', category: 'Inverter', price: '5kW Capacity | Integrated monitoring', image: '/images/inverter_product.png', description: 'Advanced micro-inverter that seamlessly converts and tracks your energy production.', status: 'Published', date: new Date().toISOString().split('T')[0] },
    { id: 3, name: 'Nova Cell Battery', category: 'Battery Storage', price: '10kWh | Deep Cycle', image: '/images/battery_product.png', description: 'Store excess solar energy for nighttime use and protect your home against local power outages.', status: 'Published', date: new Date().toISOString().split('T')[0] },
    { id: 4, name: 'Enterprise Solar Grid', category: 'Commercial Solution', price: '100kW - 10MW+ | Zero Export', image: '/images/commercial.png', description: 'Enterprise-grade solar arrays engineered strictly to eliminate commercial energy overheads.', status: 'Published', date: new Date().toISOString().split('T')[0] }
  ],
  FAQ: [
    { id: 1, question: 'How much does solar cost?', answer: 'The cost varies depending on system size, location, and specific requirements. Reach out to get a custom quote.', status: 'Published', date: new Date().toISOString().split('T')[0] },
    { id: 2, question: 'How long do solar panels last?', answer: 'Modern solar panels are designed to last 25-30 years. Our premium panels come with a comprehensive 25-year warranty.', status: 'Published', date: new Date().toISOString().split('T')[0] },
    { id: 3, question: 'Does solar work on cloudy days?', answer: 'Yes! Solar panels still generate electricity on cloudy days, though at a reduced efficiency compared to direct sunlight.', status: 'Published', date: new Date().toISOString().split('T')[0] },
    { id: 4, question: 'What is an inverter?', answer: 'An inverter is a device that converts the direct current (DC) power generated by the solar panels into alternating current (AC) power, which is the standard used by all home appliances.', status: 'Published', date: new Date().toISOString().split('T')[0] },
    { id: 5, question: 'How do solar loans work?', answer: 'Solar loans work much like standard home improvement loans, allowing you to finance the cost of your system over 5 to 20 years. In most cases, the monthly loan payment is less than your previous electricity bill!', status: 'Published', date: new Date().toISOString().split('T')[0] },
    { id: 6, question: 'Are solar panels hail resistant?', answer: 'Yes. Our premium panels are rigorously tested for extreme weather and are certified to withstand 1-inch hail striking at up to 50 mph without any micro-cracking.', status: 'Published', date: new Date().toISOString().split('T')[0] },
    { id: 7, question: 'What happens if I produce more energy than I use?', answer: 'With Net Metering, any excess energy flows back into the grid, spinning your meter backwards. Your utility company will credit your account for this excess power.', status: 'Published', date: new Date().toISOString().split('T')[0] },
    { id: 8, question: 'Can I install solar panels myself?', answer: 'While DIYkits exist, solar installations involve high-voltage electricity and roof penetrations. It is highly recommended to use certified professionals to ensure safety, efficiency, and to maintain equipment warranties.', status: 'Published', date: new Date().toISOString().split('T')[0] }
  ],
  Testimonials: [
    { id: 1, name: 'Rajeev Sharma', role: 'Homeowner', review: "I was skeptical about solar at first, but NovaSolar's 3D roof mapping completely sold me. The installation was flawless, and my electricity bill has literally dropped to zero. Highly recommend!", rating: 5, image: '', status: 'Published', date: new Date().toISOString().split('T')[0] },
    { id: 2, name: 'Ayesha Singh', role: 'Business Owner', review: "The team helped us navigate the PM Surya Ghar subsidy effortlessly. The all-black panels look incredibly premium on our modern roof. Best aesthetic investment we've ever made.", rating: 5, image: '', status: 'Published', date: new Date().toISOString().split('T')[0] },
    { id: 3, name: 'Vikram Kumar', role: 'Homeowner', review: "Their app is fantastic! I can track generation directly on my phone. We had a minor query post-installation, and their 24/7 expert support handled it within minutes. Exceptional service.", rating: 5, image: '', status: 'Published', date: new Date().toISOString().split('T')[0] }
  ],
  Blogs: [
    { id: 1, title: 'How Many Solar Panels Do You Need?', author: 'Tech Guides • 5 min read', content: 'A comprehensive guide to calculating your home energy requirements and sizing your solar array perfectly.', image: '/images/roof_3d.png', status: 'Published', date: new Date().toISOString().split('T')[0] },
    { id: 2, title: 'Monocrystalline vs Polycrystalline', author: 'Analysis • 4 min read', content: 'Which technology is right for you? We break down the cost, efficiency, and aesthetics of both options.', image: '/images/tech_flow.png', status: 'Published', date: new Date().toISOString().split('T')[0] },
    { id: 3, title: 'New Solar Incentives for 2025', author: 'Industry News • 3 min read', content: 'Discover the latest tax credits and local rebates that can significantly reduce your installation costs.', image: '/images/smart_monitor.png', status: 'Published', date: new Date().toISOString().split('T')[0] }
  ]
};

export default function ContentManager() {
  const [activeCategory, setActiveCategory] = useState('Projects');
  const [items, setItems] = useState([]);
  const [companySettings, setCompanySettings] = useState(DEFAULT_COMPANY_SETTINGS);
  
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingItem, setEditingItem] = useState(null);
  const [formData, setFormData] = useState({});

  useEffect(() => {
    if (activeCategory === 'Company Settings') {
      const saved = localStorage.getItem('solar_company_settings');
      if (saved) setCompanySettings(JSON.parse(saved));
    } else {
      const key = `solar_dataset_${activeCategory.toLowerCase()}`;
      const saved = localStorage.getItem(key);
      if (saved) {
        setItems(JSON.parse(saved));
      } else {
        const dummies = DUMMY_DATA_MAP[activeCategory] || [];
        localStorage.setItem(key, JSON.stringify(dummies));
        setItems(dummies);
      }
    }
  }, [activeCategory]);

  const saveItems = useCallback((newItems) => {
    setItems(newItems);
    localStorage.setItem(`solar_dataset_${activeCategory.toLowerCase()}`, JSON.stringify(newItems));
  }, [activeCategory]);

  const handleOpenNew = useCallback(() => {
    setEditingItem(null);
    setFormData({ status: 'Published' }); // Reset form
    setIsModalOpen(true);
  }, []);

  const handleOpenEdit = useCallback((item) => {
    setEditingItem(item);
    setFormData({ ...item });
    setIsModalOpen(true);
  }, []);

  const handleDelete = useCallback((id) => {
    saveItems(items.filter(item => item.id !== id));
  }, [items, saveItems]);

  const handleSubmit = useCallback((e) => {
    e.preventDefault();
    if (editingItem) {
      saveItems(items.map(item => item.id === editingItem.id ? { ...item, ...formData, type: activeCategory } : item));
    } else {
      const newItem = {
        id: Date.now(),
        ...formData,
        type: activeCategory,
        date: new Date().toISOString().split('T')[0]
      };
      saveItems([newItem, ...items]);
    }
    setIsModalOpen(false);
  }, [editingItem, items, formData, activeCategory, saveItems]);

  const handleSaveCompanySettings = useCallback((e) => {
    e.preventDefault();
    localStorage.setItem('solar_company_settings', JSON.stringify(companySettings));
    alert('Company Settings Saved Successfully!');
  }, [companySettings]);

  const renderModalFields = () => {
    if (activeCategory === 'Projects') {
      return (
        <>
          <label className="modal-lbl">Project Title</label>
          <input required type="text" className="modal-inp" value={formData.title || ''} onChange={e => setFormData({...formData, title: e.target.value})} />
          <label className="modal-lbl">Client Name</label>
          <input required type="text" className="modal-inp" value={formData.client || ''} onChange={e => setFormData({...formData, client: e.target.value})} />
          <label className="modal-lbl">Description</label>
          <textarea required rows="3" className="modal-inp" value={formData.description || ''} onChange={e => setFormData({...formData, description: e.target.value})} />
          <label className="modal-lbl">Image URL (Optional)</label>
          <input type="text" className="modal-inp" value={formData.image || ''} onChange={e => setFormData({...formData, image: e.target.value})} />
        </>
      );
    }
    if (activeCategory === 'Products') {
      return (
        <>
          <label className="modal-lbl">Product Name</label>
          <input required type="text" className="modal-inp" value={formData.name || ''} onChange={e => setFormData({...formData, name: e.target.value})} />
          <label className="modal-lbl">Category</label>
          <input required type="text" className="modal-inp" value={formData.category || ''} onChange={e => setFormData({...formData, category: e.target.value})} />
          <label className="modal-lbl">Price / Specs</label>
          <input required type="text" className="modal-inp" value={formData.price || ''} onChange={e => setFormData({...formData, price: e.target.value})} />
          <label className="modal-lbl">Image URL (Optional)</label>
          <input type="text" className="modal-inp" value={formData.image || ''} onChange={e => setFormData({...formData, image: e.target.value})} />
        </>
      );
    }
    if (activeCategory === 'FAQ') {
      return (
        <>
          <label className="modal-lbl">Question</label>
          <input required type="text" className="modal-inp" value={formData.question || ''} onChange={e => setFormData({...formData, question: e.target.value})} />
          <label className="modal-lbl">Answer</label>
          <textarea required rows="4" className="modal-inp" value={formData.answer || ''} onChange={e => setFormData({...formData, answer: e.target.value})} />
        </>
      );
    }
    if (activeCategory === 'Testimonials') {
      return (
        <>
          <label className="modal-lbl">Customer Name</label>
          <input required type="text" className="modal-inp" value={formData.name || ''} onChange={e => setFormData({...formData, name: e.target.value})} />
          <label className="modal-lbl">Role / Company</label>
          <input type="text" className="modal-inp" value={formData.role || ''} onChange={e => setFormData({...formData, role: e.target.value})} />
          <label className="modal-lbl">Review Message</label>
          <textarea required rows="3" className="modal-inp" value={formData.review || ''} onChange={e => setFormData({...formData, review: e.target.value})} />
          <label className="modal-lbl">Rating (1-5)</label>
          <input required type="number" min="1" max="5" className="modal-inp" value={formData.rating || 5} onChange={e => setFormData({...formData, rating: e.target.value})} />
          <label className="modal-lbl">Customer Photo URL (Optional)</label>
          <input type="text" className="modal-inp" value={formData.image || ''} onChange={e => setFormData({...formData, image: e.target.value})} />
        </>
      );
    }
    if (activeCategory === 'Blogs') {
      return (
        <>
          <label className="modal-lbl">Blog Title</label>
          <input required type="text" className="modal-inp" value={formData.title || ''} onChange={e => setFormData({...formData, title: e.target.value})} />
          <label className="modal-lbl">Author</label>
          <input required type="text" className="modal-inp" value={formData.author || ''} onChange={e => setFormData({...formData, author: e.target.value})} />
          <label className="modal-lbl">Content</label>
          <textarea required rows="6" className="modal-inp" value={formData.content || ''} onChange={e => setFormData({...formData, content: e.target.value})} />
          <label className="modal-lbl">Image URL (Optional)</label>
          <input type="text" className="modal-inp" value={formData.image || ''} onChange={e => setFormData({...formData, image: e.target.value})} />
        </>
      );
    }
    if (activeCategory === 'Messages') {
      return (
        <>
          <label className="modal-lbl">From Name</label>
          <input type="text" readOnly className="modal-inp" value={formData.name || ''} style={{ opacity: 0.8 }} />
          <label className="modal-lbl">Email Address</label>
          <input type="email" readOnly className="modal-inp" value={formData.email || ''} style={{ opacity: 0.8 }} />
          <label className="modal-lbl">Company (Optional)</label>
          <input type="text" readOnly className="modal-inp" value={formData.company || 'N/A'} style={{ opacity: 0.8 }} />
          <label className="modal-lbl">Message Body</label>
          <textarea readOnly rows="6" className="modal-inp" value={formData.message || ''} style={{ opacity: 0.8 }}></textarea>
        </>
      );
    }
    return null;
  };

  const renderTableHeaders = () => {
    switch (activeCategory) {
      case 'Projects': return <><th className="th-style">Info</th><th className="th-style">Client</th><th className="th-style">Status</th></>;
      case 'Products': return <><th className="th-style">Info</th><th className="th-style">Price</th><th className="th-style">Status</th></>;
      case 'FAQ': return <><th className="th-style">QA</th><th className="th-style">Status</th></>;
      case 'Testimonials': return <><th className="th-style">Customer</th><th className="th-style">Review</th><th className="th-style">Status</th></>;
      case 'Blogs': return <><th className="th-style">Blog Details</th><th className="th-style">Author</th><th className="th-style">Status</th></>;
      case 'Messages': return <><th className="th-style">Sender Contact</th><th className="th-style">Message Preview</th><th className="th-style">Status</th></>;
      default: return null;
    }
  };

  const renderTableCells = (item) => {
    const statusCell = (
      <td style={{ padding: '1.2rem 1.5rem', whiteSpace: 'nowrap' }}>
        <span style={{ padding: '0.3rem 0.8rem', borderRadius: '50px', fontSize: '0.8rem', fontWeight: 'bold', background: item.status === 'Published' ? 'rgba(16, 185, 129, 0.2)' : 'rgba(245, 158, 11, 0.2)', color: item.status === 'Published' ? '#34d399' : '#fbbf24' }}>
          {item.status}
        </span>
      </td>
    );

    const imageBox = item.image ? (
      <img src={item.image} alt="Thumb" style={{ minWidth: '40px', width: '40px', height: '40px', borderRadius: '8px', objectFit: 'cover' }} />
    ) : (
      <div style={{ minWidth: '40px', width: '40px', height: '40px', borderRadius: '8px', background: 'rgba(255,255,255,0.1)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.2rem' }}>🖼️</div>
    );

    switch (activeCategory) {
      case 'Projects': 
        return (
          <>
            <td style={{ padding: '1.2rem 1.5rem' }}>
              <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
                {imageBox}
                <div>
                  <div style={{ fontWeight: 'bold', color: 'white' }}>{item.title}</div>
                  <div style={{ fontSize: '0.85rem', color: '#94a3b8', maxWidth: '300px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{item.description}</div>
                </div>
              </div>
            </td>
            <td style={{ padding: '1.2rem 1.5rem', color: '#e2e8f0' }}>{item.client}</td>
            {statusCell}
          </>
        );
      case 'Products': 
        return (
          <>
            <td style={{ padding: '1.2rem 1.5rem' }}>
              <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
                {imageBox}
                <div>
                  <div style={{ fontWeight: 'bold', color: 'white' }}>{item.name}</div>
                  <div style={{ fontSize: '0.85rem', color: '#38bdf8' }}>{item.category}</div>
                </div>
              </div>
            </td>
            <td style={{ padding: '1.2rem 1.5rem', color: '#e2e8f0' }}>{item.price}</td>
            {statusCell}
          </>
        );
      case 'FAQ': 
        return (
          <>
            <td style={{ padding: '1.2rem 1.5rem' }}>
              <div style={{ fontWeight: 'bold', color: 'white', marginBottom: '0.3rem' }}>Q: {item.question}</div>
              <div style={{ fontSize: '0.85rem', color: '#94a3b8' }}>A: {item.answer}</div>
            </td>
            {statusCell}
          </>
        );
      case 'Testimonials': 
        return (
          <>
            <td style={{ padding: '1.2rem 1.5rem' }}>
              <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
                {imageBox}
                <div>
                  <div style={{ fontWeight: 'bold', color: 'white' }}>{item.name}</div>
                  <div style={{ fontSize: '0.85rem', color: '#38bdf8' }}>{item.role}</div>
                </div>
              </div>
            </td>
            <td style={{ padding: '1.2rem 1.5rem', color: '#e2e8f0' }}>
              <div style={{ fontStyle: 'italic', maxWidth: '350px' }}>"{item.review}"</div>
              <div style={{ color: '#f59e0b', fontSize: '0.9rem', marginTop: '0.5rem' }}>{'★'.repeat(item.rating)}{'☆'.repeat(5 - item.rating)}</div>
            </td>
            {statusCell}
          </>
        );
      case 'Blogs': 
        return (
          <>
            <td style={{ padding: '1.2rem 1.5rem' }}>
              <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
                {imageBox}
                <div>
                  <div style={{ fontWeight: 'bold', color: 'white' }}>{item.title}</div>
                  <div style={{ fontSize: '0.85rem', color: '#94a3b8', maxWidth: '300px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{item.content}</div>
                </div>
              </div>
            </td>
            <td style={{ padding: '1.2rem 1.5rem', color: '#e2e8f0' }}>{item.author}</td>
            {statusCell}
          </>
        );
      case 'Messages': 
        return (
          <>
            <td style={{ padding: '1.2rem 1.5rem' }}>
              <div style={{ fontWeight: 'bold', color: 'white' }}>{item.name}</div>
              <div style={{ fontSize: '0.85rem', color: '#38bdf8' }}>{item.email}</div>
              {item.company && <div style={{ fontSize: '0.8rem', color: '#64748b' }}>{item.company}</div>}
            </td>
            <td style={{ padding: '1.2rem 1.5rem', color: '#e2e8f0' }}>
              <div style={{ maxWidth: '300px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                {item.message}
              </div>
            </td>
            <td style={{ padding: '1.2rem 1.5rem', whiteSpace: 'nowrap' }}>
              <span style={{ padding: '0.3rem 0.8rem', borderRadius: '50px', fontSize: '0.8rem', fontWeight: 'bold', background: item.status === 'New' ? 'rgba(59, 130, 246, 0.2)' : 'rgba(100, 116, 139, 0.2)', color: item.status === 'New' ? '#60a5fa' : '#94a3b8' }}>
                {item.status}
              </span>
            </td>
          </>
        );
      default: return null;
    }
  };

  React.useEffect(() => {
    const style = document.createElement('style');
    style.innerHTML = `
      .th-style { padding: 1rem 1.5rem; color: #94a3b8; font-weight: 500; }
      .modal-lbl { display: block; color: #94a3b8; margin-bottom: 0.5rem; font-size: 0.9rem; margin-top: 1rem; }
      .modal-lbl:first-child { margin-top: 0; }
      .modal-inp { width: 100%; padding: 0.8rem; border-radius: 8px; border: 1px solid rgba(255,255,255,0.1); background: rgba(0,0,0,0.2); color: white; outline: none; box-sizing: border-box; }
      .modal-inp:focus { border-color: #38bdf8; }
    `;
    document.head.appendChild(style);
    return () => document.head.removeChild(style);
  }, []);

  const { currentData, currentPage, totalPages, nextPage, prevPage } = usePagination(items, 6); // Display up to 6 rows per page for admin view

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <div>
          <h2 style={{ fontSize: '1.8rem', fontFamily: 'Outfit, sans-serif', color: 'white', margin: 0 }}>Content Publisher</h2>
          <p style={{ color: '#94a3b8', margin: '0.5rem 0 0 0' }}>Manage dynamic website content across multiple sections.</p>
        </div>
      </div>

      {/* Categories Navigation */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem', marginBottom: '2rem' }}>
        <div style={{ display: 'flex', gap: '0.5rem', overflowX: 'auto', paddingBottom: '0.5rem' }}>
          {CATEGORIES.map(cat => (
            <button 
              key={cat}
              onClick={() => setActiveCategory(cat)}
              style={{
                padding: '0.6rem 1.2rem',
                borderRadius: '50px',
                border: 'none',
                cursor: 'pointer',
                fontWeight: '500',
                whiteSpace: 'nowrap',
                background: activeCategory === cat ? '#38bdf8' : 'rgba(255,255,255,0.05)',
                color: activeCategory === cat ? '#0f172a' : '#94a3b8',
                transition: 'all 0.3s'
              }}
            >
              {cat}
            </button>
          ))}
        </div>
        
        {/* Add New Button aligned horizontally with tabs */}
        {(activeCategory !== 'Company Settings' && activeCategory !== 'Messages') && (
           <button 
              onClick={handleOpenNew}
              style={{ background: '#10b981', border: 'none', color: '#0f172a', padding: '0.8rem 1.5rem', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', transition: 'all 0.3s', boxShadow: '0 4px 10px rgba(0,0,0,0.3)' }}
              onMouseOver={(e) => e.currentTarget.style.transform = 'translateY(-2px)'}
              onMouseOut={(e) => e.currentTarget.style.transform = 'translateY(0)'}
            >
              + Add New {activeCategory.replace(/s$/, '')}
            </button>
        )}
      </div>

      {activeCategory === 'Company Settings' ? (
        <form onSubmit={handleSaveCompanySettings} style={{ background: '#0f172a', padding: '2rem', borderRadius: '12px', border: '1px solid rgba(255,255,255,0.05)' }}>
          <h3 style={{ color: 'white', marginTop: 0 }}>Company Information</h3>
          
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '1.5rem' }}>
            <div style={{ gridColumn: '1 / -1' }}>
              <label className="modal-lbl">About Us Text</label>
              <textarea rows="4" className="modal-inp" value={companySettings.aboutUs} onChange={e => setCompanySettings({...companySettings, aboutUs: e.target.value})} />
            </div>
            <div>
              <label className="modal-lbl">Contact Email</label>
              <input type="email" className="modal-inp" value={companySettings.email} onChange={e => setCompanySettings({...companySettings, email: e.target.value})} />
            </div>
            <div>
              <label className="modal-lbl">Contact Phone</label>
              <input type="text" className="modal-inp" value={companySettings.phone} onChange={e => setCompanySettings({...companySettings, phone: e.target.value})} />
            </div>
            <div style={{ gridColumn: '1 / -1' }}>
              <label className="modal-lbl">Office Address</label>
              <input type="text" className="modal-inp" value={companySettings.address} onChange={e => setCompanySettings({...companySettings, address: e.target.value})} />
            </div>
          </div>
          
          <div style={{ marginTop: '2rem', display: 'flex', justifyContent: 'flex-end' }}>
            <button type="submit" style={{ background: '#f59e0b', color: '#0f172a', border: 'none', padding: '0.8rem 2rem', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer' }}>Update Config</button>
          </div>
        </form>
      ) : (
        <>
          <div style={{ background: '#0f172a', borderRadius: '12px', border: '1px solid rgba(255,255,255,0.05)', overflowX: 'auto' }}>
            <table style={{ width: '100%', minWidth: '800px', borderCollapse: 'collapse', textAlign: 'left', color: 'white' }}>
              <thead>
                <tr style={{ background: 'rgba(0,0,0,0.3)' }}>
                  {renderTableHeaders()}
                  <th className="th-style">Date Added</th>
                  <th className="th-style" style={{ textAlign: 'right' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                <AnimatePresence>
                  {currentData.map(item => (
                    <motion.tr 
                      key={item.id}
                      initial={{ opacity: 0, x: -10 }}
                      animate={{ opacity: 1, x: 0 }}
                      exit={{ opacity: 0, x: 20 }}
                      style={{ borderBottom: '1px solid rgba(255,255,255,0.05)' }}
                    >
                      {renderTableCells(item)}
                      <td style={{ padding: '1.2rem 1.5rem', color: '#cbd5e1' }}>{item.date}</td>
                      <td style={{ padding: '1.2rem 1.5rem', textAlign: 'right', whiteSpace: 'nowrap' }}>
                        <motion.button 
                          onClick={() => {
                            if(activeCategory === 'Messages' && item.status === 'New') {
                              saveItems(items.map(i => i.id === item.id ? { ...i, status: 'Read' } : i));
                            }
                            handleOpenEdit(item);
                          }} 
                          whileHover={{ scale: 1.05 }}
                          whileTap={{ scale: 0.95 }}
                          style={{ background: 'rgba(96, 165, 250, 0.1)', border: '1px solid rgba(96, 165, 250, 0.2)', color: '#60a5fa', cursor: 'pointer', marginRight: '0.8rem', padding: '0.4rem 1rem', borderRadius: '6px', fontSize: '0.85rem' }}
                        >
                          {activeCategory === 'Messages' ? 'View' : 'Edit'}
                        </motion.button>
                        <motion.button 
                          onClick={() => handleDelete(item.id)} 
                          whileHover={{ scale: 1.05 }}
                          whileTap={{ scale: 0.95 }}
                          style={{ background: 'rgba(248, 113, 113, 0.1)', border: '1px solid rgba(248, 113, 113, 0.2)', color: '#f87171', cursor: 'pointer', padding: '0.4rem 1rem', borderRadius: '6px', fontSize: '0.85rem' }}
                        >
                          Delete
                        </motion.button>
                      </td>
                    </motion.tr>
                  ))}
                  {currentData.length === 0 && (
                    <tr>
                      <td colSpan="4" style={{ padding: '3rem', textAlign: 'center', color: '#94a3b8' }}>No {activeCategory.toLowerCase()} available.</td>
                    </tr>
                  )}
                </AnimatePresence>
              </tbody>
            </table>

            {totalPages > 1 && (
              <div style={{ display: 'flex', justifyContent: 'flex-end', alignItems: 'center', gap: '1rem', padding: '1rem 1.5rem', borderTop: '1px solid rgba(255,255,255,0.05)' }}>
                <button onClick={prevPage} disabled={currentPage === 1} style={{ background: currentPage === 1 ? 'transparent' : 'rgba(255,255,255,0.05)', color: 'white', border: '1px solid rgba(255,255,255,0.1)', padding: '0.5rem 1rem', borderRadius: '6px', cursor: currentPage === 1 ? 'not-allowed' : 'pointer' }}>Previous</button>
                <span style={{ color: '#94a3b8', fontSize: '0.9rem' }}>Page {currentPage} of {totalPages}</span>
                <button onClick={nextPage} disabled={currentPage === totalPages} style={{ background: currentPage === totalPages ? 'transparent' : 'rgba(255,255,255,0.05)', color: 'white', border: '1px solid rgba(255,255,255,0.1)', padding: '0.5rem 1rem', borderRadius: '6px', cursor: currentPage === totalPages ? 'not-allowed' : 'pointer' }}>Next</button>
              </div>
            )}
          </div>
        </>
      )}

      {/* Modern Modal */}
      <AnimatePresence>
        {isModalOpen && (
          <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.6)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100, backdropFilter: 'blur(5px)' }}>
            <motion.div 
              initial={{ scale: 0.9, opacity: 0, y: 30 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.9, opacity: 0, y: -20 }}
              transition={{ type: 'spring', bounce: 0.3 }}
              style={{ background: '#0f172a', width: '100%', maxWidth: '600px', maxHeight: '90vh', overflowY: 'auto', borderRadius: '16px', padding: '2rem', border: '1px solid rgba(255,255,255,0.1)', boxShadow: '0 25px 50px rgba(0,0,0,0.5)' }}
            >
              <h3 style={{ margin: '0 0 1.5rem 0', color: 'white', fontFamily: 'Outfit, sans-serif' }}>{editingItem ? `Edit ${activeCategory.replace(/s$/, '')}` : `Create New ${activeCategory.replace(/s$/, '')}`}</h3>
              
              <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                <div style={{ maxHeight: '60vh', overflowY: 'auto', paddingRight: '0.5rem' }}>
                  {renderModalFields()}
                  {activeCategory !== 'Messages' && (
                    <>
                      <label className="modal-lbl" style={{ marginTop: '1rem' }}>Visibility Status</label>
                      <select 
                        value={formData.status} onChange={e => setFormData({...formData, status: e.target.value})}
                        className="modal-inp"
                      >
                        <option value="Published">Published</option>
                        <option value="Draft">Draft</option>
                      </select>
                    </>
                  )}
                </div>

                <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '1rem', marginTop: '1.5rem', paddingTop: '1rem', borderTop: '1px solid rgba(255,255,255,0.1)' }}>
                  {activeCategory === 'Messages' ? (
                     <button type="button" onClick={() => setIsModalOpen(false)} style={{ background: '#3b82f6', color: 'white', border: 'none', cursor: 'pointer', padding: '0.8rem 1.5rem', borderRadius: '8px', fontWeight: 'bold' }}>Close Viewing</button>
                  ) : (
                    <>
                      <button type="button" onClick={() => setIsModalOpen(false)} style={{ background: 'transparent', color: '#94a3b8', border: 'none', cursor: 'pointer', padding: '0.8rem 1.5rem', borderRadius: '8px' }}>Cancel</button>
                      <button type="submit" style={{ background: '#38bdf8', color: '#0f172a', border: 'none', cursor: 'pointer', padding: '0.8rem 1.5rem', borderRadius: '8px', fontWeight: 'bold' }}>Save Changes</button>
                    </>
                  )}
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}
